// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxuoikvhwfmonqtzduyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dW9pa3Zod2Ztb25xdHpkdXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTAzNDUsImV4cCI6MjA3MTE2NjM0NX0.L1DWKrgL1Zlq984uzxr5hpOnq1eqfWllq2ZYgq8l3Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});